spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/test1?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    
    
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: false
    generate-ddl: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.ddl-auto: update
      hibernate.generate-ddl: true
      hibernate.jdbc.batch_size: 50
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
      hibernate.generate_statistics: false
     
environment:
  a: Hola desde GitHub!
